In [2]:
import pandas as pd
import numpy as np

In [5]:
def sigmoid(x):
    1/(1+np.exp**(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

In [9]:
class nn():
    def __init__(self,hidden,input,output):
        self.input=input
        self.hidden=hidden
        self.output=output
        self.weights_hidden=np.random.rand(self.input,self.hidden)
        self.weights_output=np.random.rand(self.hidden,self.output)
        self.bias_hidden = np.zeros((1, self.hidden))
        self.bias_output = np.zeros((1, self.output))
    def forward(self,inputs):
        self.hidden_input = np.dot(inputs, self.weights_hidden) + self.bias_hidden
        self.hidden_output = sigmoid(self.hidden_input)

        # Hidden to output layer
        self.output_input = np.dot(self.hidden, self.weights_output) + self.bias_output
        self.predictions = sigmoid(self.output_input)

        return self.predictions
    def backward(self, inputs, targets, learning_rate):
        
        output_error = targets - self.predictions
        output_delta = output_error * sigmoid_derivative(self.predictions)

        hidden_error = output_delta.dot(self.weights_hidden_output.T)
        hidden_delta = hidden_error * sigmoid_derivative(self.hidden_output)

        self.weights_hidden_output += self.hidden_output.T.dot(output_delta) * learning_rate
        self.bias_output += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
        self.weights_input_hidden += inputs.T.dot(hidden_delta) * learning_rate
        self.bias_hidden += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate
    def train(self, inputs, targets, epochs, learning_rate):
        for epoch in range(epochs):
            predictions = self.forward(inputs)
            self.backward(inputs, targets, learning_rate)

            if epoch % 100 == 0:
                loss = np.mean(np.square(targets - predictions) / 2)
                print(f'Epoch {epoch}, Loss: {loss}')    
np.random.seed(42)
num_samples = 100
input_data = np.random.rand(num_samples, 5)
output_data = np.random.rand(num_samples, 3)

print("Input Data:")
print(input_data[:5])
print("\nOutput Data:")
print(output_data[:5])

input_size = 5
hidden_size = 7
output_size = 3

# Create and train the neural network
model = nn(input_size, hidden_size, output_size)
model.train(input_data, output_data, epochs=10000, learning_rate=0.1)

# Test the trained model
predictions = model.forward(input_data)
print("Predictions after training:")
print(predictions)
        

Input Data:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]

Output Data:
[[0.69816171 0.53609637 0.30952762]
 [0.81379502 0.68473117 0.16261694]
 [0.91092718 0.82253724 0.94979991]
 [0.72571951 0.6134152  0.41824304]
 [0.93272848 0.86606389 0.04521867]]


ValueError: shapes (100,5) and (7,5) not aligned: 5 (dim 1) != 7 (dim 0)